### ISSUE TITLE
Photos edited and saved in place with another app aren't opened by Polarr

### ISSUE THREAD

**Issue by interstateone** [Polarrco/polarr_ios_android_support#11]
If I edit a photo and save it in place in the photo library (so there is now an original and edited version) the Polarr app will continue to display and open the original version of the photo instead of the edited version. This seems like incorrect (or at least not desired for my case) behaviour to me, where what I was hoping would happen is I would edit a photo (e.g. for skew with SKRWT) and save the photo in place, then continue with other editing functionality in Polarr without needing to duplicate any photos.

**Comment by din** [comment]
I believe there is no way to open photos edited in place with other applications in our own just because Photos.framework doesn't support such thing. So if we really do want to open an edited version of a picture, we couldn't use Photos.framework methods just to do that since it only supports editing of the original image.

**Comment by interstateone** [comment]
Ah okay. I checked Snapseed, which I don't normally use, and it seems to be able to show thumbnails for and open the edited versions in the library. From a quick search it seems like the PHImageRequestOptionsVersion enum provides this functionality. Sorry, I'm not near a computer for a while so I can't provide a more conclusive suggestion. Anyways, you've probably already seen this, so maybe you're using a different mechanism to open photos that doesn't support this?
